### ISSUE TITLE
Azure RM Inventory plugin does not return all hosts all the time

### ISSUE THREAD

**Issue by amitsharma-31** [ansible/ansible_collections_azure#1614]
##### SUMMARY
Syncing an Ansible inventory using the Azure RM Inventory plugin does not return all hosts all the time.
We sync our inventory on a schedule, but sometimes it barely returns any hosts.
For example last time it only captured 10 out of some 150+ hosts. Next run was again able to list all 150+ hosts

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm (azure inventory plugin)

##### ANSIBLE VERSION

```
ansible [core 2.15.9]
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.venv/bin/ansible
  python version = 3.9.19 (main, May 16 2024, 08:45:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (~/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
azure.azcollection             2.2.0
```

**Comment by amitsharma-31** [comment]
It appears Ansible is making too many calls to Azure and is being throttled. Either Ansible should lower the number of calls or implement exponential backoff retry as described: https://learn.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines. 

The changes are required to avoid throttling need to be configured.

Issue observed :- throttling (HTTP 429 errors) on the failed time slot. The throttling occurred on the ARM (Azure Resource Management) layer, not on the Resource Provider (Virtual Machines) layer. More details on throttling can be found at https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling

There is similar issue but way older https://github.com/ansible-collections/azure/issues/224

**Comment by p3ck** [comment]
I'm trying to understand where it's failing.  I can see that the batch processing only handles 200 status code but I would expect it to fail in the batch request and it does seem to handle non 202 (it's a post call to /batch).

I think it would be helpful to add the following to the inventory plugin and see if we get any errors back.

```
diff --git a/plugins/inventory/azure_rm.py b/plugins/inventory/azure_rm.py
index 73d8ec7..79d984b 100644
--- a/plugins/inventory/azure_rm.py
+++ b/plugins/inventory/azure_rm.py
@@ -423,6 +423,7 @@ class InventoryModule(BaseInventoryPlugin, Constructable):
     # use the undocumented /batch endpoint to bulk-send up to 500 requests in a single round-trip
     #
     def _process_queue_batch(self):
+        errors = []
         while True:
             batch_requests = []
             batch_item_index = 0
@@ -463,6 +464,10 @@ class InventoryModule(BaseInventoryPlugin, Constructable):
                     # FUTURE: error-tolerant operation mode (eg, permissions)
                     # FUTURE: store/handle errors from individual handlers
                     result.handler(r['content'], **result.handler_args)
+                else:
+                    errors.append("Error fetching: {0}, status code: {1}".format(result.url, status_code))
+        if len(errors) > 0:
+            raise AnsibleError(str(errors))
 
     def _send_batch(self, batched_requests):
         url = '/batch'
```

**Comment by p3ck** [comment]
Can you also try setting default_host_filters to [] in your inventory.yml

default_host_filters: []

Comment from: https://github.com/ansible-collections/azure/issues/224#issuecomment-810045941

**Comment by p3ck** [comment]
I am not able to recreate the original issue since I don't have that many hosts in my azure instance.  But I tested the following pr with the inventory integration tests and it passes.

https://github.com/ansible-collections/azure/pull/1649

I followed the code from GenericRestClient which also handles long running processes (202).

**Comment by Rickmarges** [comment]
Hello @p3ck, I'm a coworker of Amit.

I've added the code snippet you've mentioned in the first comment and the results are below:
<details><summary>Error results</summary>
<code>
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with auto plugin: ['Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instance
View, status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instance
View, status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instanceView,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instanceView,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instance
View, status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instanceView,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Compute/virtualMachines/vm-name/instanceView,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
......
Many more lines
.......
status code: 429', 'Error fetching:
/subscriptions/subscription-id/resourceGroups/resource-group/providers/Microsoft.Network/networkInterfaces/nic-name,
status code: 429']
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign
this is a YAML file.
[WARNING]: Unable to parse /home/user/inventory_test/test_azure_rm.yaml as
an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
@all:
  |--@ungrouped:
</code>
</details> 

Regarding your second comment; When adding this to the existing inventory setup I get no hosts at all. 

And when testing the fixes proposed in #1649 we get the following error:
```
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with auto plugin: 'PipelineResponse' object has no attribute 'body'
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/user/inventory_test/test_azure_rm.yaml
with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign
this is a YAML file.
[WARNING]: Unable to parse /home/user/inventory_test/test_azure_rm.yaml as
an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
@all:
  |--@ungrouped:
```

**Comment by p3ck** [comment]
Thank you for your patience with me. 

I've updated the PR in #1649 with a minor change to handle the error.  Can you try the updated version?

Thanks

**Comment by Rickmarges** [comment]
Hello @p3ck, 
I've tried with the updated version and no erros now.
However, also no hosts unfortunately

**Comment by p3ck** [comment]
I've attempted to add Backoff and retry logic to the send_batch/process_batch code of the inventory plugin.  This passes the inventory integration tests but @Rickmarges If you are able to test I would appreciate it since I'm not able to create enough hosts to trigger the issue.

**Comment by Rickmarges** [comment]
When testing the new version of the code I still get no hosts. I've added some print statements locally to see the requests, and now I'm seeing some HTTP 500 errors (rather than the 429). This results in the code never reaching the `batch_retry` if-statement.
@p3ck please let me know what (if any) output you want to see to narrow down the issue.

In addition; what we are noticing as well is that the plugin creates a lot of unnecessary requests. First it gets all VMs and then starts getting information about those VMs and NICs. Even for VMs that will be excluded from the inventory because of filters provided in the inventory configuration. If the filters would be checked upfront (after listing all VMs; if possible) that would save on a lot of requests

**Comment by Rickmarges** [comment]
Another small addition; I've tried to change the code to change `elif status_code == 429` to just an `else` to also catch the 500 erros. This time I didn't see any status_codes other than 200 (which is also weird, because I'm debugging before the if), but still `ansible-inventory` wasn't able to generate a graph (thus no hosts parsed).

To paint the picture a bit better of why we run into this, the subscription where we are using/scanning has 535 VMs and most (if not all) has 2 NICs. And out of those 535 VMs, we (currently) only need 201.

**Comment by Fred-sun** [comment]
@amitsharma-31 Since I cannot reproduce this problem locally, could you please help me provide your use case? I would like to confirm it, thank you!

**Comment by Rickmarges** [comment]
@Fred-sun our use case is as  follows:

We're migrating our workload from a Chef managed environment to Ansible managed in Azure. We're rapidly deploying new systems (and resource groups) in multiple subscriptions (depending on the DTAP-environment). 
Each (new, ansible-managed) VM gets a set of 3 tags. Based on those tags we assign the VMs to the correct organisation within AAP. The tags also help differentiate between our old and new worklaod.

One of the tags is responsible for assigning it to an inventory group.  That group contain specific variables required to configure the system in a way to deploy the workload/application. 
Because of the rapid increase in VMs, as well as allow for autoscaling (using the same group and thus same variables), it's unmanageable to make a static inventory with all hosts. Hence our choice to use the Azure RM inventory plugin to create a dynamic inventory.

The problem we are facing is rate-limiting due to the amount of VMs that have to be gathered (as well as all their info). Since we're not finished with out migration, this problem will only get bigger and bigger. As stated prior to this, we currently have 201 Ansible managed VMs. That amount will rapidly increaase and cause even more rate-limit issues.

Hopefully this helps you in understanding our use case as well as show why this is a problem for us.

**Comment by p3ck** [comment]
Can you provide the following??

What is your ANSIBLE_INVENTORY pointing to?

And what are the contents of that yml?

For example, in our test setup we use:
```
---
plugin: azure.azcollection.azure_rm
conditional_groups:
  azure: true
exclude_host_filters:
  - location not in ['eastus', 'northcentralus']
  - powerstate != 'running'
  - not (tags['Deployment-Method'] | default('Exclude') == 'Ansible' and tags['Automation-Method'] | default('Exclude') == 'Ansible')
fail_on_template_errors: True
plain_host_names: true
...
```

**Comment by Rickmarges** [comment]
@p3ck I htink I owe you an apology...
Your last version of the plugin **is** working. I just had a faulty filter which caused every host to be excluded.
With your changes we do get every host back consistently without errors. Thank you very much for your efforts!

On another note, with the retry enabled, it does take a lot of time (up to 15 minutes).
I'm not sure if this is normal or if this can be sped up. But this is also not the end of the world.

**Comment by p3ck** [comment]
You have made my day!!  Apology accepted!  :-)

I am looking into adding filtering at the vm_list level which should speed things up for you.  But it may be a while since I am going on Holiday next week.

**Comment by Rickmarges** [comment]
No worries! First enjoy your holiday! That's more important 😉

**Comment by p3ck** [comment]
I made one minor change to have it catch more then just 429 status code.  I took the same list of status codes that the azure-sdk-for-python used in the retry policy.  So this should also catch and retry on 500 errors as well.

**Comment by Fred-sun** [comment]
@amitsharma-31 @Rickmarges I have added a retry mechanism in PR #1657, can you help to try it in your environment? I suspect that we sent a lot of requests, although the server returned 202, but finally for these requests did not return the data we need, resulting in the VM did not return all, thank you!

**Comment by Rickmarges** [comment]
@Fred-sun I've tried the code provided in #1657, however, after 30 minutes it just ran into a timeout with the following error:
>The server did not successfully process our reques

Besides it not working, I feel like #1649 (created by @p3ck) is doing the same steps, but in a more dynamic/flexible way (not retrying the complete request, but only failed ones)

**Comment by Fred-sun** [comment]
@Rickmarges I understand what you mean. I just want to confirm that if 202 is not returned after the request is sent, it is possible that the service may not return correctly in the end, causing us to fail to get the VM. Thank you!

**Comment by Rickmarges** [comment]
@Fred-sun do you have any insights on when the fix for this gets released?

**Comment by Fred-sun** [comment]
@Rickmarges This will be released soon, as soon as we have merged the latest patches, thank you!

**Comment by p3ck** [comment]
Hi @Fred-sun Do you need anything from me to do the release? 

Thanks

**Comment by Fred-sun** [comment]
@p3ck The release time will be confirmed after discussion with @xuzhang3  tomorrow. Thank you!

**Comment by jbjornel** [comment]
@Fred-sun @xuzhang3 Greetings, was there any release time confirmed after discussion last week? Thanks!

**Comment by Rickmarges** [comment]
@Fred-sun @xuzhang3 Any update on this?

**Comment by xuzhang3** [comment]
@Rickmarge  this issue has been fixed by PR #1649  and released in `v2.7.0`
