### ISSUE TITLE
azure_rm_loadbalancer and azure_rm_networkinterface contain functionality which should have been removed for Ansible 2.9

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible_collections_azure#77]
##### SUMMARY
Search for `will be removed in 2.9` and `version='2.9'` next to `deprecate()` calls.

(I started removal in ansible/ansible#65749 but it turns out that the integration tests make heavy use of the functionality. This should better be done by someone who knows more about Azure.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer
azure_rm_networkinterface

##### ANSIBLE VERSION
```
2.9
2.10
```

**Comment by Fred-sun** [comment]
@felixfontein It may fixed by https://github.com/ansible-collections/azure/pull/223, please check! Thank you very much!

**Comment by felixfontein** [comment]
The changes in #223 for these two modules do not seem to touch anything related to deprecation / removal.

**Comment by Fred-sun** [comment]
@felixfontein Could you please elaborate on your requirements? This will help solve the problem you are encountering! Thank you very much!

**Comment by Fred-sun** [comment]
@felixfontein Do you still have this question? If not, it is recommended to close it temporarily. Thank you very much!

**Comment by felixfontein** [comment]
@Fred-sun the issue is obviously not resolved, so I don't see why this should be closed.
